#pragma once

#define SIZE 10.f

///TAMAÑO EN PX DE LA VENTANA
#define W_WINDOW_PX 800
#define H_WINDOW_PX 600

///TAMAÑ˜O EN CELDAS DE LA VENTANA
#define W_WINDOW_TITLE 80
#define H_WINDOW_TITLE 60

///TAMAÑO EN CELDAS DE UNA ZONA DE MAPA
#define W_WINDOW_TITLE_PART 40
#define H_WINDOW_TITLE_PART 30
